"""Agrego isactive para los usuarios

Revision ID: 129e8e8f7fd3
Revises: 61f99dda22ef
Create Date: 2026-01-07 20:52:00.969613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129e8e8f7fd3'
down_revision: Union[str, Sequence[str], None] = '61f99dda22ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_at')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
